---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: thorntail-example
    app.kubernetes.io/name: thorntail-example
  name: thorntail-example
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: thorntail-example
---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: thorntail-example
    app.kubernetes.io/name: thorntail-example
  name: thorntail-example
spec:
  to:
    kind: Service
    name: thorntail-example
---

apiVersion: v1
kind: DeploymentConfig
metadata:
  name: thorntail-example
  labels:
    app.kubernetes.io/instance: thorntail-example
    app.kubernetes.io/name: thorntail-example
spec:
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - thorntail-example
        from:
          kind: ImageStreamTag
          name: 'thorntail-example:latest'
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/ca-key: '/var/run/secrets/kubernetes.io/serviceaccount/ca-bundle/service-ca.crt'
        vault.hashicorp.com/agent-inject-secret-application.yaml: secret/example
        vault.hashicorp.com/agent-inject-template-application.yaml: |
          {{- with secret "secret/example" -}}
          secret:
            example:
              password: {{ .Data.password }}
          {{- end }}
        vault.hashicorp.com/role: example
      labels:
        app: thorntail-example       
    spec:
      containers:
        - args:
            - '-s/vault/secrets/application.yaml'
          command:
            - /opt/run-java/run/run-java.sh
          name: thorntail-example
          image: "thorntail-example:latest"
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 3
          volumeMounts:
          - mountPath: /var/run/secrets/kubernetes.io/serviceaccount/ca-bundle
            name: vault-cabundle
      volumes:
      - configMap:
          name: vault-agent-cabundle
        name: vault-cabundle

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: vault-agent-cabundle
  labels:
    app.kubernetes.io/instance: vault-agent
    app.kubernetes.io/name: vault-agent
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
data: {}