apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent-config
data:
  vault-agent-config: |-
    pid_file = "/var/run/secrets/vaultproject.io/pid"

    auto_auth {
            method "kubernetes"  {
                    type = "kubernetes"
                    mount_path = "auth/kubernetes"
                    config = {
                            role = "example"
                            jwt = "@/var/run/secrets/kubernetes.io/serviceaccount/token"
                    }
            }

            sink "file" {
                    type = "file"
                    config = {
                            path = "/var/run/secrets/vaultproject.io/token"
                    }
            }
    }

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: thorntail-example
  name: thorntail-example
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: thorntail-example
---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: thorntail-example
  name: thorntail-example
spec:
  to:
    kind: Service
    name: thorntail-example
---

apiVersion: v1
kind: DeploymentConfig
metadata:
  name: thorntail-example
spec:
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - thorntail-example
        from:
          kind: ImageStreamTag
          name: 'thorntail-example:latest'
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - vault-secret-fetcher
        from:
          kind: ImageStreamTag
          name: 'vault-secret-fetcher:latest'
          namespace: openshift
  replicas: 1
  template:
    metadata:
      labels:
        app: thorntail-example       
    spec:
      containers:
        - args:
            - '-s/var/run/secrets/vaultproject.io/application.yaml'
          command:
            - /opt/run-java/run-java.sh
          name: thorntail-example
          image: "thorntail-example:latest"
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 3
          volumeMounts:
          - mountPath: /var/run/secrets/vaultproject.io
            name: vault-agent-volume
        - image: vault:latest
          name: vault-agent
          args:
          - agent
          - -log-level=debug
          - -config=/vault/config/agent.config
          env:
          - name: SKIP_SETCAP
            value: 'true'
          - name: VAULT_ADDR
            value: https://vault.hashicorp-vault.svc:8200
          - name: VAULT_CAPATH
            value: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
          volumeMounts:
          - mountPath: /vault/config/agent.config
            subPath: agent.config
            name: vault-config
          - mountPath: /var/run/secrets/vaultproject.io
            name: vault-agent-volume
        - image: vault-secret-fetcher:latest
          name: vault-secret-fetcher
          args:
            - start
          env:
            - name: LOG_LEVEL
              value: 'DEBUG'
            - name: VAULT_ADDR
              value: https://vault.hashicorp-vault.svc:8200
            - name: VAULT_CAPATH
              value: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
            - name: VAULT_TOKEN
              value: /var/run/secrets/vaultproject.io/token
            - name: VAULT_SECRET
              value: secret/example
            - name: PROPERTIES_FILE
              value: /var/run/secrets/vaultproject.io/application.yaml
          imagePullPolicy: Always
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/run/secrets/vaultproject.io
              name: vault-agent-volume
      volumes:
      - name: vault-agent-volume
        emptyDir:
          medium: Memory
      - configMap:
          items:
            - key: vault-agent-config
              path: agent.config
          name: vault-agent-config
        name: vault-config