apiVersion: v1
kind: Service
metadata:
  name: vault-agent
  labels:
    app: vault-agent
spec:
  ports:
  - name: vault
    port: 8200
  selector:
    app: vault
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: vault-agent
  name: vault-agent
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vault-agent
    spec:
      containers:
      - image: vault:latest
        name: vault-agent
        ports:
        - containerPort: 8200
          name: vaultport
          protocol: TCP
        args:
        - agent
        - -log-level=debug
        - -config=/vault/config/agent.config
        env:
        - name: SKIP_SETCAP
          value: 'true'
        - name: "VAULT_ADDR"
          value: "https://vault.hashicorp.svc:8200"
        - name: "VAULT_CAPATH"
          value: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
        volumeMounts:
        - mountPath: /vault/config/agent.config
          subPath: agent.config
          name: vault-config
      volumes:
      - configMap:
          items:
            - key: vault-agent-config
              path: agent.config
          name: vault-agent-config
        name: vault-config
